name: Build, Test, and Analyse

on:
  workflow_call:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            !~/.nuget/packages/unwanted
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build -c Debug --no-restore

      - name: Test
        run: dotnet test -c Debug --no-restore --collect:"XPlat Code Coverage" --logger "trx;LogFilePrefix=TestResults" --results-directory TestResults -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: upload TestResults
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ github.sha }}
          path: |
            ./TestResults/*.trx
            ./TestResults/**/coverage.opencover.xml
