name: On Pull Request

on:
  pull_request:
    branches:
      - develop
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '7.0.102' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --debug Debug --no-restore -nowarn:1591
    
    - name: Run NUnit tests
      run: dotnet test --no-build --configuration Debug --filter FullyQualifiedName~Answer.King.IntegrationTests.Tests.AnswerKingPostOrder.ProductOrder*
